name: Deploy
on:
  workflow_dispatch:
    inputs:
      target:
        description: "where to deploy"
        type: choice
        options: [staging , production]
jobs:
  deplopy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying to ${{ inputs.target }}
