name: ci
on: [push , pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "running test"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'ref/head/main'
    steps:
      - uses: actions/checkout@v4
      - run: echo "deploying because this is main"
